cloud:
  aws:
    credentials:
      accessKey: AKIASBJPUR7YXWRLBXC3
      secretKey: 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
    s3:
      bucket: bje-s3-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false