version: '3'
services:
  nginx:
    container_name: live/front
    image: "nginx:latest"
    ports:
     - "80:80"
     - "443:443"
    networks:
     - backend
    restart: always
    volumes: 
     - /nginx/default.conf:/etc/nginx/conf.d/default.conf
     - /var/log/nginx:/var/log/nginx # log파일의 위치
     - /etc/letsencrypt:/etc/letsencrypt #letsencrypt폴더 위치
    environment: 
     - TZ=Asia/Seoul
networks: 
  backend:
    driver: bridge